cpi_list <- c(
  "Meat",
  "Fish",
  "Eggs",
  "Fresh milk",
  "Fresh fruit",
  "Bakery products",
  "Fresh vegetables",
  "Coffee",
  "Food purchased from restaurants",
  "Baby foods",
  "Rent",
  "Mortgage interest cost",
  "Electricity",
  "Water",
  "Natural gas",
  "Fuel oil and other fuels",
  "Homeowners' replacement cost",
  "Homeowners' maintenance and repairs",
  "Homeowners' home and mortgage insurance",
  "Internet access services",
  "Telephone services",
  "Pet food and supplies",
  "Furniture",
  "Household appliances",
  "Child care services",
  "Household cleaning products",
  "Clothing",
  "Footwear",
  "Watches",
  "Jewellery",
  "Public transportation",
  "Rental of passenger vehicles",
  "Purchase of passenger vehicles",
  "Gasoline",
  "Passenger vehicle maintenance and repair services",
  "Passenger vehicle insurance premiums",
  "Air transportation",
  "Eye care services",
  "Dental care services",
  "Prescribed medicines",
  "Non-prescribed medicines",
  "Toiletry items and cosmetics",
  "Computer equipment, software and supplies",
  "Toys, games and hobby supplies",
  "Toiletry items and cosmetics",
  "Newspapers",
  "Books and reading material",
  "Tuition fees",
  "School textbooks and supplies",
  "Recreational cannabis",
  "Alcoholic beverages",
  "Cigarettes"
)

category_list <- c(
  "All-items",
  "Recreation, education and reading",
  "Alcoholic beverages, tobacco products and recreational cannabis",
  "Food",
  "Shelter",
  "Household operations, furnishings and equipment",
  "Clothing and footwear",
  "Transportation",
  "Health and personal care"
)

geo_list <- c(
  "Canada",
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Nova Scotia",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan"
)
