cpi_list <- c(
  "Meat",
  "Fish, seafood and other marine products",
  "Dairy products and eggs",
  "Fresh fruit",
  "Bakery products",
  "Vegetables and vegetable preparations",
  "Coffee",
  "Food purchased from restaurants",
  "Rented accommodation",
  "Owned accommodation",
  "Electricity",
  "Water",
  "Natural gas",
  "Fuel oil and other fuels",
  "Internet access services",
  "Telephone services",
  "Pet food and supplies",
  "Furniture",
  "Household appliances",
  "Financial services",
  "Child care services",
  "Household cleaning products",
  "Sporting and exercise equipment",
  "Clothing",
  "Footwear",
  "Clothing accessories, watches and jewellery",
  "Public transportation",
  "Rental of passenger vehicles",
  "Purchase of passenger vehicles",
  "Gasoline",
  "Passenger vehicle parts, maintenance and repairs",
  "Passenger vehicle insurance premiums",
  "Air transportation",
  "Eye care services",
  "Dental care services",
  "Prescribed medicines",
  "Non-prescribed medicines",
  "Home entertainment equipment, parts and services",
  "Travel services",
  "Toiletry items and cosmetics",
  "Digital computing equipment and devices",
  "Toys, games and hobby supplies",
  "Toiletry items and cosmetics",
  "Books and reading material",
  "Tuition fees",
  "Recreational cannabis",
  "Alcoholic beverages",
  "Cigarettes"
)

category_list <- c(
  "All-items",
  "Recreation, education and reading",
  "Alcoholic beverages, tobacco products and recreational cannabis",
  "Food",
  "Shelter",
  "Household operations, furnishings and equipment",
  "Clothing and footwear",
  "Transportation",
  "Health and personal care"
)

geo_list <- c(
  "Canada",
  "Alberta",
  "British Columbia",
  "Manitoba",
  "New Brunswick",
  "Newfoundland and Labrador",
  "Nova Scotia",
  "Ontario",
  "Prince Edward Island",
  "Quebec",
  "Saskatchewan"
)
