name: consumer-price-index

on: 
  schedule:
    - cron: '35 12 22 06 *'
    - cron: '35 12 20 07 *'
    - cron: '35 12 16 08 *'
    - cron: '35 12 20 09 *'
    - cron: '35 12 19 10 *'
    - cron: '35 13 16 11 *'
    - cron: '35 13 21 12 *'
    - cron: '35 13 17 01 *'
    - cron: '35 13 21 02 *'
    - cron: '35 13 21 03 *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
    - name: Setup R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: consumer-price-index/scripts
    - name: Run data script
      run: Rscript consumer-price-index/scripts/cpi.R
    - name: Commit data
      run: |-
        git config user.name "gn-scraper"
        git config user.email "actions@users.noreply.github.com"
        git add consumer-price-index/**/*
        timestamp=$(date -u)
        git commit -m "Consumer price index data: ${timestamp}" || exit 0
        git push
