name: covid-variants

# New data is released on Friday afternoons, so the
# job runs every 20 mins from 2:20-7pm EST on Fridays
on: 
  workflow_dispatch:
  schedule:
    - cron: '19,39,59 19-23 * * 5'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        install-r: false
    - name: Setup R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: covid-variants/scripts
    - name: Run data script
      run: Rscript covid-variants/scripts/variant-data.R
    - name: Commit data
      run: |-
        git config user.name "gn-scraper"
        git config user.email "actions@users.noreply.github.com"
        git add covid-variants/**/*
        timestamp=$(date -u)
        git commit -m "Variant data: ${timestamp}" || exit 0
        git push
